### ISSUE TITLE
Image broken on production server

### ISSUE THREAD

**Issue by fr-olivier** [MattWilcox/Adaptive-Images#160]
Hello,

After many tests, I managed to install Adaptive-Images in local environment (I had to increase the php memory to allow resizing images 2048px wide, by adding "php_value memory_limit 64M" in the .htaccess, for those who have the same problem).

But once on the production server, the image appears to be broken (the broken image icon), and the Chrome console displays this error:
Resource interpreted as Image but transferred with MIME type text/html: "http://DOMAIN_NAME/ai/img2.jpg".

I guess it's a matter of .htaccess configuration, but I don't know much about Apache.
Do you know what's wrong?

Thanks,
François

**Comment by MattWilcox** [comment]
Hmm, it's definitely a problem with your servers configuration, but I'd be guessing that you need to ensure your server is sending the right MIME types for image files.
