### ISSUE TITLE
Internet Explorer Wrong Screen Size (minor issue) with multi-screen

### ISSUE THREAD

**Issue by rafmix** [MattWilcox/Adaptive-Images#163]
Hi,

in case of multi-screen, the cookie store always the main screen resolution. In my case, I had 3 screens and the main screen has a resolution of 768*1366, so the cookies set the resolution to 1366 instead I opened IE on the second screen with a reolution of 1920*1200.
If I define the second screen (1920*1200) as main screen, on opened IE, the cookie store the reolution of 19200.

Not a big issue, just cool to know if you check that Adaptive Images works or not :)

regards
raf

**Comment by MattWilcox** [comment]
I don't believe there's anything that can be done about this, as far as I'm aware it's entirely down to the browser how it deals with multiple monitors.
