### ISSUE TITLE
Attempted Chmod 0666 in SendImage()

### ISSUE THREAD

**Issue by peterpilgrim** [MattWilcox/Adaptive-Images#171]
Hi Matt

I attempted an enhancement of your Adaptive Image.
I have requirement to allow the images to be group and/or world writable in the *ai-cache* folder.

So I wrote this addition:

> $cache_file_permissions = "666"; // We want the files to world write in a shared hosting solution; allows the customer remove cache independent of shared host admin

in the configuration, I found all sort of issues trying to chmod in PHP. This was on the road to a suggestion or patch, which has been waylaid. Admittedly, I have more Java expertise than PHP. So I tried this enhancement with brute force hack.

```php
/* helper function: Send headers and returns an image. */
function sendImage($filename, $browser_cache) {
  // chmod($filename, 0666 ); 
  ...
}
```

This should work I thought. It doesn't the images send back to the client are blank. I do not know how to debug PHP. The image files are definitely now world deletable, but I cannot explain why the rest of the PHP function sendImage would sent blank images. How can changing the permissions of the cache file cause this bunch of zeros?

I using Mac OS X Yosemite and the built-in Apache 2.4 server
```
36248152        0 drwxrwxrwx    3 peterpilgrim     _www                  102  6 Nov 09:28 ai-cache
36507663        0 drwxr-xr-x    3 _www             _www                  102  6 Nov 09:28 ai-cache/360
36507664        0 drwxr-xr-x    8 _www             _www                  272  6 Nov 09:28 ai-cache/360/images
36507839       40 -rw-rw-rw-    1 _www             _www                20021  6 Nov 09:28 ai-cache/360/images/firecracker.gif
36507790       40 -rw-rw-rw-    1 _www             _www                18710  6 Nov 09:28 ai-cache/360/images/digital-transformation.gif
36507838       32 -rw-rw-rw-    1 _www             _www                14908  6 Nov 09:28 ai-cache/360/images/software-craftman.jpg
36507665       88 -rw-rw-r
```

Any ideas?

**Comment by MattWilcox** [comment]
Hmm, I have no experience with chmod in PHP I'm sorry, not something I've ever needed to do and I'm not sure what knock-on effects this would have. My PHP knowledge is rusty (this project was the first and last one I've done in PHP for years :/

Anyone else got any insight into this?

**Comment by staabm** [comment]
> I found all sort of issues trying to chmod in PHP

What exactly is the issue? 

For some servers it might make sense to add a config param to adaptive.php so admins can configure the access-rights files should be created with. It could default to `false` so chmod will not be done at all and regular `umask` is used (like it is right now)

**Comment by peterpilgrim** [comment]
In the end, I used a different solution to adaptive.php and therefore chmod was a moot point. I found that my images were no rendering correctly and so I wanted more control and used the popular <picture> shim code.

**Comment by staabm** [comment]
Ok, so we can close here?
