### ISSUE TITLE
Exempt ordinary thumbnails from going through AI

### ISSUE THREAD

**Issue by jorisw** [MattWilcox/Adaptive-Images#174]
Hi,

Surely many blogs have image galleries and other use cases for displaying thumbnails, which shouldn't be loaded at image sizes that cover the longest edge of the screen size.

I have remedied this by defining a thumbnail size in my WordPress' functions.php, giving it a name (e.g. '400x400') that is appended to the filename by WordPress, which I then exclude from AI in .htaccess like so:

```
# BEGIN adaptive images

RewriteCond %{REQUEST_URI} wp-content/uploads/
RewriteCond %{REQUEST_URI} !400x400
RewriteRule .(?:jpe?g|gif|png)$ adaptive-images.php

# END adaptive images
```

If you have any suggestions for a better approach, by all means share, or if this is the right approach, maybe you could add this to the FAQ.

**Comment by MattWilcox** [comment]
The normal approach would be to have thumbnails in their own directory and exempt that directory from AI. This works as well if you must have the thumbnails in the same directory :)
