### ISSUE TITLE
AI on adaptive-images.com doesn't work

### ISSUE THREAD

**Issue by NormanHoehne** [MattWilcox/Adaptive-Images#175]
Hey guys,

I was considering to implement Adaptive-Images on my own Website and wanted to know if it works.
So I've tried to open the demo site on adaptive-images.com with Galaxy S3 and Kindle Fire HDX and saved two of the delivered images on both devices.

Because of the fact, that the file size of those saved images doesn't differ from the original size, I assume that this isn't really working. Or is this an issue because of the high resolutions of the tested devices?

Best regards
Norman

**Comment by Vlasterx** [comment]
Galaxy S3 already has highest supported resolution in that demo. If you make more breakpoints in supplied php file, you would have seen the difference. But here is the problem - with so many high resolution mobile devices, we end up with images that are much larger in both dimensions and size than desktop PC resolutions. End result is quite the oposite of desired one - smaller images for mobile, larger for desktop, so we have larger images for mobile, smaller for desktop.

I like the simplicity of this solution, but it would benefit from recognizing high dpi displays.

**Comment by NormanHoehne** [comment]
Thank you Vlasterx for your answer!

I guessed as much. What a pity!
Since seperate mobile websites are almost gone i think it is inevitable to deliver optimized images to each type of devices. I hoped that AI would be my solution :-/
