### ISSUE TITLE
Demo site serving original image

### ISSUE THREAD

**Issue by Pandahisham** [MattWilcox/Adaptive-Images#176]
I went to the demo site , it sent me the original sizes , regardless of viewport sizes ,

**Comment by K4T** [comment]
From official page:
"Adaptive Images does NOT work on your browser window size, resizing your browser will have no effect on the size of images that are downloaded. It works on the screen size. The reason for this is to avoid poor caching behaviour; if you're on a large screen with a small window and AI were to deliver the small image, that image would be cached by your browser. As soon as you maximised the window the image would obviously be too small, and the browser doesn't know it needs to re-request the image."
