### ISSUE TITLE
Serve images based on column width

### ISSUE THREAD

**Issue by bsadecki** [MattWilcox/Adaptive-Images#180]
I'm building a site with BootStrap where the desktop viewport serves ~200px wide thumbnails because it's divided into three columns. Tablet and mobile serve full width images. So I need it to restrict by column size rather than screen resolution.

I noticed that @kollinger created this [pull](https://github.com/MattWilcox/Adaptive-Images/pull/125) which uses BootStrap 2 but I'm not really sure about its implementation. It looks like it relies on the span element being used in the filename? And that's not an option.

Anyway, this is a great tool but is it just not the right one for this task?

**Comment by MattWilcox** [comment]
This isn't the right project for that task, unless you want to try the modified version. Likely you should be trying out the new srcset and sizes properties on a regular img tag for that use case.
