### ISSUE TITLE
Abandonware?

### ISSUE THREAD

**Issue by uhlhosting** [MattWilcox/Adaptive-Images#207]
Is this ever possible to be still up to date since no updated in decade?

**Comment by josfaber** [comment]
Yes imho. Although nowadays one can also render various sizes during compilation of a project, doing this on the fly in a 'caching' kinda way is still a very good method.

The code might have to be adapted for a PHP 8.1 environment, but I wouldn't be surprised if this still just runs.

**Comment by MattWilcox** [comment]
Please see https://github.com/MattWilcox/Adaptive-Images#project-status

As @josfaber mentions - technically it might still work. But really there are many other options around today which solve this problem better.

**Comment by uhlhosting** [comment]
@josfaber @MattWilcox any simillar solution for wordpress that you could maybe recommend. In all my years havent seen one. And is weird cause I just come accross this one too.

**Comment by MattWilcox** [comment]
https://developer.wordpress.org/apis/responsive-images/ is what you'd be looking for, though I haven't used Wordpress in over a decade.
