### ISSUE TITLE
how do I know if Adaptive-Images is working?

### ISSUE THREAD

**Issue by tim-peterson** [MattWilcox/Adaptive-Images#52]
Sorry that is such a dumb question, but I installed the files and am confused on how to know whether AI is actually working. Can someone point me to a quick test?

I have an iPhone and am decent with Chrome Developer tools but not exactly sure where to look to check image size as I change device-width.

thanks,
tim

**Comment by davert318** [comment]
I tried this and it does not seem to be working. 

Elsewhere, I found a script that uses rsync to find images that are not in a destination folder, then adds resizes from your images folder and moves them to a destination, so you can have a folder for photos that are small, medium, and original size. Where I have issues is figuring out how to adjust .htaccess to pull from the small folder for any browser user agent with the word "phone" in it (which gets 90%+ of mobile cases in my experience).
